services:
  postgres:
    image: postgres:14.0
    restart: unless-stopped
    container_name: db-stronzo-tpf-core
    environment:
      - POSTGRES_USER=stronzo
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=core
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
