trigger:
  branches:
    include:
      - main

variables:
  - group: Stronzo - General IaC
  - group: Stronzo - TPF.Core - Dev
  - name: buildDirectory
    value: "$(Build.ArtifactStagingDirectory)/build"
  - name: outputDir
    value: $(Build.ArtifactStagingDirectory)
  - name: downloadedPackageDirectory
    value: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
  - name: namespace
    value: stronzo-tapegandofogo
  - name: appName
    value: core
  - name: solution
    value: TPF.Core.sln

pool: Azure.Pool.Stronzo

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: UseDotNet@2
            displayName: "Use Dotnet 6.0.x"
            inputs:
              packageType: "sdk"
              version: "6.0.x"

          - task: DotNetCoreCLI@2
            displayName: "Dotnet Restore"
            inputs:
              command: "restore"
              projects: $(solution)

          - task: DotNetCoreCLI@2
            displayName: "Dotnet Build"
            inputs:
              command: "custom"
              custom: "build"
              projects: $(solution)
              arguments: "-c $(configuration) --no-restore"

          - task: DotNetCoreCLI@2
            displayName: "Dotnet Publish"
            inputs:
              command: "publish"
              publishWebProjects: false
              projects: $(solution)
              arguments: '-c $(configuration) -o "$(buildDirectory)" --no-build --no-restore'
              zipAfterPublish: false

          - task: ArchiveFiles@2
            displayName: "Archive files"
            inputs:
              rootFolderOrFile: $(buildDirectory)/s
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(outputDir)/$(Build.BuildId).zip
              replaceExistingArchive: true

          - publish: $(outputDir)
            displayName: "Publish artifact"
            artifact: drop

  - template: deployment.yml
    parameters:
      environment: dev
      dependsOn: Build
      namespace: $(namespace)
      appName: $(appName)
      subscription: StronzoDefaultSubscription
      packageDirectory: $(downloadedPackageDirectory)
